language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      compiler: gcc

before_install:
  - brew install libgosu sdl2_image sdl2_mixer

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: true
