language: cpp

os: osx
osx_image: xcode11

addons:
  homebrew:
    packages:
      - sdl2
      - sdl2_image
      - sdl2_mixer

script:
  - mkdir build
  - cd build
  - cmake .. -DAV_SDL2=On
  - cmake --build .
