language: cpp

os: osx
osx_image: xcode10.2

addons:
  homebrew:
    packages:
      - cmake
      - libgosu
      - sdl2_image
      - sdl2_mixer

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
