language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: osx
      osx_image: xcode8.2
      compiler: gcc

before_install:
  - brew install libgosu

install:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: true
